### ISSUE TITLE
Source code for entire app

### ISSUE THREAD

**Issue by rustyshakelford2** [asperon/smoothcalendar#36]
Would you consider posting the source code for the entire app? With the upcoming blocking of older api target versions on Android 14 it is going to stop working. I would like to be able to update it.

**Comment by asperon** [comment]
There is already a 2.0 version in beta, so no worries
On 2023-02-09 16:32:38, rustyshakelford2 ***@***.***> wrote:
Would you consider posting the source code for the entire app? With the upcoming blocking of older api target versions on Android 14 it is going to stop working. I would like to be able to update it.

**Comment by rustyshakelford2** [comment]
Wonderful! Thank you for the reply. I would be happy to beta test when the time comes. I have had this on my home screen for many years. I appreciate your work.

**Comment by asperon** [comment]
You can sign up by following the instructions on https://smoothcalendar.org/
On 2023-02-09 18:03:25, rustyshakelford2 ***@***.***> wrote:
Wonderful! Thank you for the reply. I would be happy to beta test when the time comes. I have had this on my home screen for many years. I appreciate your work.

**Comment by rustyshakelford2** [comment]
I tried that but the google groups link says "Content unavailable"
